digitallinguistics/spec

.travis.yml, package-lock.json, package.json
=> DEV: run upload script during Travis build

.github/CONTRIBUTING.md, .github/PULL_REQUEST_TEMPLATE.md, .github/README.md, docs/index.html
#166
- Title: `LABEL: description (#000)`
- Description
- Changelog: `LABEL: description (closes #000)`
=> DOCS: add (hidden) developer note to general readme

.eslintrc.yml, .github/README.md, README.md, docs/index.html, package-lock.json, package.json, schemas/yaml/Utterance.yml
#283
This pull request updates the links in the readme for maintainability.
- Title: `LABEL: description (#000)`
- Description
- Changelog: `LABEL: description (closes #000)`
=> update links in readme

docs/schemas/Translation.html, schemas/json/Translation.json, schemas/yaml/Translation.yml
Add string compatability to Translation, Minor version update, update description of Translation
https://github.com/digitallinguistics/spec/issues/297
Add string compatibility to Translation object. Minor version update.
NEW: add string compatibility to Translation
UPDATE: update Translation version to 3.1.0
=> Add string compatability to Translation

docs/CNAME, docs/index.html, docs/schemas/Lexeme.html, schemas/json/Lexeme.json, schemas/yaml/Lexeme.yml
https://github.com/digitallinguistics/spec/issues/269
Updated the Lexeme Schema to the noteType field could take pragmatic as a value.
=> Add pragmatic notetype

docs/schemas/Morpheme.html, schemas/json/Morpheme.json, schemas/yaml/Morpheme.yml
Clarify Morpheme.transcription as Phonemic
Clarify Morpheme.gloss is CAPS for grammatical glosses.
Minor version bump
https://github.com/digitallinguistics/spec/issues/280
https://github.com/digitallinguistics/spec/issues/278
Adjusted the descriptions of fields in the Morpheme schema.
CHANGE: update Morpheme.transcription description
CHANGE: update Morpheme.gloss description
=> Update Morpheme descriptions

docs/schemas/Lexeme.html, schemas/json/Lexeme.json, schemas/yaml/Lexeme.yml
https://github.com/digitallinguistics/spec/issues/279
Added an enumerated string field to the Lexeme schema, taking either grammatical or lexical as values.
=> Add lexemeType to Lexeme

.github/README.md
JUST PART:
https://github.com/digitallinguistics/spec/issues/301
Updated example language tags to IETF format.
UPDATE: update example language tags
=> Update user README.md

docs/index.html, docs/schemas/MultiLangString.html, docs/schemas/Translation.html, package-lock.json, package.json, schemas/json/MultiLangString.json, schemas/json/Translation.json, schemas/yaml/MultiLangString.yml, schemas/yaml/Translation.yml, test/MultiLangString.test.js, test/Translation.test.js
https://github.com/digitallinguistics/spec/issues/301
Added an IETF regex to the language tag for MultiLangString and Translation objects. Added test files for both MultiLangString and Translation. Updated example data and documentation.
TEST: add test files to spec for Translation and MultiLangString
REMOVE: remove abbreviation references in Translation and MultiLangString
NEW: add IETF regex for language tags in Translation and MultiLangString
DOCS: update developer README.md
DOCS: update example data in Translation and MultiLangString
UPDATE: major version update for Translation and MultiLangString
=> Implement IETF language tags

docs/schemas/Utterance.html, schemas/json/Utterance.json, schemas/yaml/Utterance.yml
Update example data
https://github.com/digitallinguistics/spec/issues/317
CHANGE: update `Utterance.literalTranslation` to `Utterance.literal`
CHANGE: update example data
=> Change literalTranslation to literal

docs/schemas/Location.html, package.json, schemas/json/Location.json, schemas/yaml/Location.yml, test/.eslintrc.yml, test/Lexeme.test.js, test/utilities/GeoJSON.json, test/utilities/ajv.js
https://github.com/digitallinguistics/spec/issues/329
**This should fix all of the broken PRs. However, it will have a conflict with the changes made to the Language-8.4 PR version of `ajv.js`.**
Pulled the GeoJSON schema offline and into the test library. The `ajv.js` file now accesses an offline version of the GeoJSON schema, which is stored in the `test/utilities` library. This will eliminate a dependency on an unchanging URL.
NEW: add `GeoJSON.json` to `test/utilities`
CHANGE: update `getGeoJSONSchema()` function in `ajv.js` to reference offline version of schema
CHANGE: update `getGeoJSONSchema()` function description
CHANGE: update GeoJSON url in `Location` schema
=> GeoJSON FIX

.github/README.md
DOCS: Update README.md citation year to 2019
=> Update README.md citation year

docs/schemas/Person.html, schemas/json/Person.json, schemas/yaml/Person.yml
https://github.com/digitallinguistics/spec/issues/276
Implemented Person.startDate and Person.endDate as specified in the issue.
NEW: Create Person.startDate
NEW: Create Person.endDate
UPDATE: Update example data
CHANGE: Minor version bump
=> Implement Person.date fields

docs/schemas/BibliographicReference.html, schemas/json/BibliographicReference.json, schemas/yaml/BibliographicReference.yml
https://github.com/digitallinguistics/spec/issues/328
https://github.com/digitallinguistics/spec/issues/327
https://github.com/digitallinguistics/spec/issues/282
Added a `citationKey` field and a `link` field. Also clarified the difference between `link` and `url`. Added example data that is meant to be temporary.
NEW: add `BibliographicReference.link`
NEW: add `BibliographicReference.citationKey`
CHANGE: update `BibliographicReference.url` description and title for clarity
UPDATE: update example data
CHANGE: minor version bump 
=> Bibliographic Reference 5.3

docs/schemas/Location.html, schemas/json/Location.json, schemas/yaml/Location.yml
https://github.com/digitallinguistics/spec/issues/277
Added a new date field to the Location schema. It is functionally identical to the dateCreated and Modified fields, but with a different description.
=> added date field to Location

docs/schemas/Language.html, docs/schemas/Orthography.html, schemas/json/Language.json, schemas/json/Orthography.json, schemas/yaml/Language.yml, schemas/yaml/Orthography.yml
https://github.com/digitallinguistics/spec/issues/312
https://github.com/digitallinguistics/spec/issues/313
Added an `Orthography.grapheme.description` field for a user-friendly guide to pronouncing a grapheme. Updated and renamed `Orthography.grapheme.pronunciation` to be compatible with a single string in addition to an array of strings.
NEW: add `Orthography.grapheme.description` field
CHANGE: rename `Orthography.grapheme.pronunciations` > `pronunciation`
CHANGE: make `pronunciation` field compatible for both array of strings and single string
UPDATE: update example data in `Orthography` and `Language`
CHANGE: minor version bump to 3.3.0
=> Orthography 3.3

README.md, docs/schemas/Lexeme.html, schemas/json/Lexeme.json, schemas/yaml/Lexeme.yml
This PR adds information to the developer readme about using NDJSON format with DLx. (closes #347)
=> add NDJSON to developer readme

schemas/yaml/Language.yml
This PR requires at least one property on `Language.name`.
=> require at least one property on Language.name

.github/PULL_REQUEST_TEMPLATE.md, schemas/json/Language.json, schemas/json/Location.json, schemas/json/Morpheme.json, schemas/json/Phoneme.json, schemas/json/Text.json, schemas/json/Translation.json, schemas/json/Utterance.json, schemas/json/Word.json, schemas/yaml/Language.yml
closes #379 
Added the AES scale, found [here](https://glottolog.org/langdoc/status), to the status field for a Language.
NEW: add AES scale to Language status field
BUILD: update .json files
=> Add Language.status AES field

schemas/json/WordSet.json, schemas/json/index.js, schemas/yaml/WordSet.yml
closes #344 
This is the prototype version of the WordSet schema.
NEW: add WordSet schema
=> Add WordSet schema

schemas/json/Annotation.json, schemas/json/Phoneme.json, schemas/yaml/Annotation.yml, schemas/yaml/Phoneme.yml
closes #383 
FIX: typo in Phoneme
FIX: incorrect property descriptions in Annotation
=> Fix small bugs

schemas/json/LexemeForm.json, schemas/yaml/LexemeForm.yml
closes #406 
@dwhieb Check that the example data is accurate, I figured it was 50/50
NEW: LexemeForm.abstract
=> Add LexemeForm.abstract

schemas/json/Language.json, schemas/json/LexemeForm.json, schemas/json/Text.json, schemas/json/WordTemplate.json, schemas/yaml/Text.yml
closes #408
NEW: add Text.language as a DBreference to a Language
=> Add Text.language

schemas/json/Language.json, schemas/yaml/Language.yml
closes #407 
Adds new `glottocode` field and adds a notice that the old `glottolog` field will be removed in v2.0.
NEW: Language.glottocode
CHANGE: deprecate Language.glottolog
=> add Language.glottocode
